language: python

matrix:
  include:
    - python: 3.7-dev
      dist: xenial
      env: TOXENV=py37-test
    - python: 3.7-dev
      dist: xenial
      env: TOXENV=lint
    - python: 3.7-dev
      dist: xenial
      env: TOXENV=py37-interop
      sudo: true
      before_install:
        - wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz
        - sudo tar -C /usr/local -xzf go1.12.6.linux-amd64.tar.gz
        - export GOPATH=$HOME/go
        - export GOROOT=/usr/local/go
        - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
        - ./install_interop_go_pkgs.sh

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox

notifications:
    slack: py-libp2p:RK0WVoQZhQXLgIKfHNPL1TR2
